[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "firebase-admin>=7.1.0",
    "flask>=3.1.2",
    "google-generativeai>=0.8.5",
    "pytelegrambotapi>=4.27.0",
    "requests>=2.32.4",
]
